---
- name: Create typical OpenVZ container
  hosts: vz
  roles:
    - createct

- name: Add container to ansible management
  hosts: 127.0.0.1
  connection: local
  roles:
    - sshpass

# This playbook from github with small fixes
# https://github.com/ansible/ansible-examples/tree/master/wordpress-nginx_rhel7
- name: Install WordPress, MariaDB, Nginx, and PHP-FPM
  hosts: wordpress
  roles:
    - common
    - mariadb
    - nginx
    - php-fpm
    - wordpress
