---
- name: Update template cache
  command: "/usr/sbin/vzpkg update cache {{ ostemplate }}"

- name: Create virtuozzo container
  command: "{{ prlctl }} create {{ name }} --config {{ osconfig }} --vmtype=ct"

- name: Setup IP
  command: "{{ prlctl }} set {{ name }} --ipadd {{ ip }}"

- name: Setup nameserver
  command: "{{ prlctl }} set {{ name }} --nameserver {{ ns }}"

- name: Setup hostname
  command: "{{ prlctl }} set {{ name }} --hostname {{ hostname }}"

- name: Add root password
  command: "{{ prlctl }} set {{ name }} --userpasswd root:{{ password }}"

- name: Add CT to autostart
  command: "{{ prlctl }} set {{ name }} --onboot yes"
  notify: start container
  notify: add ssh key
