---
- name: Update templates cache
  command: /usr/sbin/vzpkg update cache {{ ostemplate }}

- name: Create virtuozzo containers
  command: {{ prlctl }} create {{ name }} --config {{ osconfig }} --vmtype=ct

- name: Setup IP's, nameservers, hostnames
  command: {{ prlctl }} {{ name }} --ipadd {{ ip }}

- name: Setup nameservers
  command: {{ prlctl }} {{ name }} --nameserver {{ ns }}

- name: Setup hostnames
  command: {{ prlctl }} {{ name }} --hostname {{ hostname }}

- name: Add root passwords
  command: {{ prlctl }} {{ name }} --userpasswd root:{{ password }}

- name: Add CT's to autostart
  command: {{ prlctl }} {{ name }} --onboot yes
  notify: start containers
